name: Develop Branch

on:
  push:
    branches:
      - 'develop'

jobs:
  build_angular:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build

  package_and_deploy:
    name: Publish Docker Img to Docker Hub
    runs-on: ubuntu-20.04
    needs: [build_angular]
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - run: docker image build -t ${DOCKER_REPO} .
      - run: docker image tag ${DOCKER_REPO} cvchavez2/mk-tictactoe-ui
      - run: docker image push cvchavez2/mk-tictactoe-ui
      - run: docker logout

#  build_and_deploy_Azure:
#    name: Publish Docker Img to Azure CR
#    runs-on: ubuntu-20.04
#    needs: [build_and_test_angular]
#    steps:
#      - name: 'Checkout Github Action'
#        uses: actions/checkout@v2
#
#      - name: 'Login via Azure CLI'
#        uses: azure/login@v1
#        with:
#          creds: ${{secrets.AZURE_CREDENTIALS}}
#
#      - name: 'Build and Push'
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{secrets.REGISTRY_LOGIN_SERVER}}
#          username: ${{secrets.REGISTRY_USERNAME}}
#          password: ${{secrets.REGISTRY_PASSWORD}}
#      - run: |
#          docker build . -t ${{secrets.REGISTRY_LOGIN_SERVER}}/mktictactoeui:${{github.sha}}
#          docker push ${{secrets.REGISTRY_LOGIN_SERVER}}/mktictactoeui:${{github.sha}}
#
#      - name: 'Deploy to Azure Container Instances'
#        uses: 'azure/aci-deploy@v1'
#        with:
#          resource-group: ${{secrets.RESOURCE_GROUP}}
#          dns-name-label: ${{secrets.RESOURCE_GROUP}}${{github.run_number}}
#          image: ${{secrets.REGISTRY_LOGIN_SERVER}}/mktictactoeui:${{github.sha}}
#          registry-login-server: ${{secrets.REGISTRY_LOGIN_SERVER}}
#          registry-username: ${{secrets.REGISTRY_USERNAME}}
#          registry-password: ${{secrets.REGISTRY_PASSWORD}}
#          name: aci-mktictactoeui
#          location: 'central us'
